### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by f35f22fan** [miqid/atom-rustsym#6]
[Enter steps to reproduce:]

1. Installed rustsym, then Ctrl+R
2. Started typing... got the error below:
3. Note in case it matters: rustsym package for Atom was installed before Rust's rustsym.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: KDE neon
**Thrown From**: [rustsym](https://github.com/miqid/atom-rustsym) package 0.4.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:28

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at exit (/packages/rustsym/lib/symbols-searcher.js:68:67)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1048999)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1049153)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1047755)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -0:10.3.0 symbols-view:toggle-file-symbols (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-language-rust 0.14.1 
cursor-blink-interval 0.3.1 
language-rust 0.4.12 
rustsym 0.4.1 
stop-cursor-blinking 1.0.1 
symbols-list 2.5.4 
symbols-tree-view 0.14.0 
```

**Comment by miqh** [comment]
Hello @f35f22fan,

I haven't touched this package for a while so bear with me.

Did you eventually work around the error you logged above (i.e. reloading Atom)?

I suspect the error might be triggered in relation to where Rust source is located on the file system.

**Comment by f35f22fan** [comment]
Thanks, I'm closing this because apparently rustsym is no longer installed, I have only installed these which do all I need:
atom-ide-ui
language-rust
rustfmt
symbols-tree-view
